pagopa/rtd-ms-sender-auth

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- Dockerfile
- LICENSE
- README.md
- docker-compose.yml
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/RtdMsSenderAuthApplication.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/controller/DefaultRestController.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/controller/RestControllerImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/model/FileMetadata.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/RtdMsSenderAuthApplicationTests.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/controller/RestControllerTest.java
Description
This PR adds the basic repository structure with spring boot starter dependencies.
> [RTD-190] Creation of repository basic structure

- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- manifests/deployment.yml
- manifests/service.yml
This PR proposes to add the code review and deploy pipelines and manifest files.
- Add code review pipeline
- Add deploy pipeline
- Add manifest files
The repository has currently no CI/CD pipelines. To improve the automation it is better to add the pipelines.
> [RTD-191] Creation of code review and deploy pipelines

- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/controller/DefaultRestController.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/controller/RestControllerImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/controller/SenderRestController.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/controller/SenderRestControllerImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/repository/SenderAuthRepository.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/service/SenderAuthService.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/service/SenderAuthServiceImpl.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/RtdMsSenderAuthApplicationTests.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/controller/RestControllerTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/service/SenderAuthServiceImplTest.java
This PR proposes to implement and expose the endpoints necessary to store and retrieve the sender code and the relative key associated.
- Add endpoints in the rest controller
- Implement service
- Add unit tests for controller and service
The sender-auth must expose one endpoint to store the mapping between api key and sender code, and one endpoint to retrieve the sender code from the api key.
> [RTD-193] Creation of endpoints to store and retrieve data

- lombok.config
This PR proposes to add lombok configuration to exclude it from code coverage calculation.
- Add `lombok.config` file
Sonarcloud fails the minimum code coverage because it consider the lombok annotations.
> [RTD-327] add lombok config to exclude it from code coverage

- README.md
- postman/local_sender_auth_integration_test.postman_collection.json
This PR proposes to add a collection postman to allow the run of an integration test suite.
- Add collection postman
- Update README with commands to run the collection
The sender auth does not have an integration test suite at the moment.
> [RTD-326] Add collection postman for local integration test

- postman/local_sender_auth_integration_test.postman_collection.json
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/controller/RestExceptionHandler.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/controller/SenderRestController.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/exception/InternalIdAlreadyAssociatedException.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/exception/RecordNotFoundException.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/service/SenderAuthServiceImpl.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/controller/RestControllerTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/service/SenderAuthServiceImplTest.java
This PR proposes to improve the error handling of rest api. In particular the body responses have been customized to replace the default responses with timestamp.
- Improved error handling in rest controller
The responses of sender auth are supposed to be easy managed by apim and therefore it is required to avoid the timestamp in the body.
> [RTD-449] Improve exceptions handling in rest api

- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/repository/SenderAuthRepository.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/service/SenderAuthService.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/service/SenderAuthServiceImpl.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/repository/SenderAuthServiceIntegrationTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/service/SenderAuthServiceImplTest.java
This PR adds authorization functionality to sender-auth at service level
- update sender-auth service interface
- service unit test
- narrow integration between service and mongodb
> [RTD-612] Authorization service

- postman/sender_auth_component_test.postman_collection.json
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/controller/RestExceptionHandler.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/controller/SenderRestController.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/controller/SenderRestControllerImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/domain/exception/SenderUnauthorized.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/controller/RestControllerTest.java
This PR adds authorization endpoint through rest api
- authorization endpoint
- update postman collection tests
> [RTD-613] Authorize Endpoint

- .devops/deploy-pipelines.yml
Implemented rollout restart to make tests run successfully
> Deploy to UAT

- Dockerfile
This PR proposes to enable Application Insights agent.
> [RTD-748] Enable Application Insights agent

- .devops/deploy-pipelines.yml
- pom.xml
This PR proposes to promote the new feature in UAT.
> Promote to UAT

- Dockerfile
- manifests/deployment.yml
This PR proposes to add Application Insights secrets and config map reference to the microservice deployment.
- add references in manifest
- remove unnecessary java option (will be taken from the config map)
> [RTD-765] Add appinsights and config map reference

- manifests/deployment.yml
- pom.xml
This PR proposes to bump and pin the version of embedded mongo dependency in order to fix a recent bug reported here: [https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/427](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/427)
- pin version
Tests were failing, with this update they run as usual.
> [RTD-773] Pin embedded mongo version

- .devops/cstar-rtd-code-review-pipelines.yml
- .devops/cstar-rtd-deploy-pipelines.yml
> chore: [RTD-1053] Add code review and deploy pipelines to new aks

- helm/rtd/.helmignore
- helm/rtd/Chart.yaml
- helm/rtd/values-dev.yaml
- helm/rtd/values-prod.yaml
- helm/rtd/values-uat.yaml
- helm/rtd/values.yaml
> [RTD-1051] Add Helm for all environments

- .devops/cstar-rtd-deploy-pipelines.yml
- postman/sender_auth_component_test_aks.postman_collection.json
> [RTD-1127] Adapt test to new aks

- helm/rtd/values-prod.yaml
- helm/rtd/values-uat.yaml
> fix: fix helm chart uat and prod

- Dockerfile
This PR proposes to bump Application Insights agent version.
> chore: [RTD-1209] Bump Application Insights agent version

- .devops/cstar-rtd-deploy-pipelines.yml
> fix postmanEnvFile prod pipeline

- .devops/cstar-rtd-deploy-pipelines.yml
> fix postmanEnvFile prod pipeline (#44)

- .devops/cstar-rtd-code-review-pipelines.yml
> chore: code review pipeline

- .github/workflows/anchore.yml
- Dockerfile
- pom.xml
This PR proposes to add a GitHub workflow to scan security.
- New GitHub workflow
With this change we can monitor the vulnerability of the code in this repository.
> chore: [RTD-1211] Add vulnerability scan

- helm/rtd/values.yaml
> fix: [RTD-1454] Fix AppInsights problem

- postman/sender_auth_component_test.postman_collection.json
- postman/sender_auth_component_test_aks.postman_collection.json
This PR proposes to fix the component test assertion
> chore: [RTD-1508] fix assertion on component test

- .devops/cstar-rtd-deploy-pipelines.yml
* [RTD-1567] trigger deploy pipeline on relevant paths changes
[RTD-1567]: https://pagopa.atlassian.net/browse/RTD-1567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Promotion to UAT, update pipeline deploy trigger

- .github/workflows/anchore.yml
- .github/workflows/pr-title.yml
- .github/workflows/release.yml
This PR pins the sha of github actions used by workflows.
- anchore.yml now uses pinned actions
- release.yml now uses pinned actions
- pr-title.yml now uses pinned actions
> chore: [RTD-1632] Pinning workflow actions

- Dockerfile
- Dockerfile.native
This PR pins the sha of base docker image used to build microservice images.
- base build and runtime image of Dockerfile
- base build and runtime image of Dockerfile.native
> chore: [RTD-1633] Pin docker base images

- .github/workflows/anchore.yml
- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- Dockerfile
- Dockerfile.native
This PR aligns github action & docker images pinning to UAT environment
> chore: Pin github actions & docker image to UAT

- .github/workflows/anchore.yml
- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- Dockerfile
- Dockerfile.native
* chore: [RTD-1632] Pinning workflow actions (#65)
* chore: [RTD-1633] Pin docker base images (#66)
[RTD-1632]: https://pagopa.atlassian.net/browse/RTD-1632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1633]: https://pagopa.atlassian.net/browse/RTD-1633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Pin github actions & docker image to PROD

- .github/workflows/release.yml
This PR try to fix the pinning of semantic release plugins.
Tested through act (local github action runner)
> fix: [RTD-1648] pinning for semantic release plugins

- helm/rtd/values-dev.yaml
- helm/rtd/values-prod.yaml
- helm/rtd/values-uat.yaml
This PR proposes to set the `forceRedeploy` parameter in helm chart deployment.
The purpose is to trigger the pod re-creation after deploy.
> chore: [RTD-1212] explicit forceRedeploy in deployment

- Dockerfile.native
- helm/rtd/values.yaml
- pom.xml
This PR proposes to force the container to run as non root user. It adds a new user to the image and set it as default, then instruct k8s to run that user and group.
> fix: [RTD-1696] run container as non-root user

- Dockerfile
- Dockerfile.native
- helm/rtd/values-prod.yaml
- align values prod image tag to latest version
- update docker image to solve many CVE
> fix: [RTD-1800] align values prod image tag

- Dockerfile.native
> fix: [RTD-1801] change from alpine to ubuntu LTS image

- Dockerfile
- Dockerfile.native
- helm/rtd/values-dev.yaml
- helm/rtd/values-prod.yaml
- helm/rtd/values-uat.yaml
- helm/rtd/values.yaml
- pom.xml
> fix: Promotion to UAT - non-root container

- .devops/cstar-rtd-deploy-pipelines.yml
- .github/workflows/anchore.yml
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/telemetry/AppInsightConfig.java
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
> chore: [RTD-1957] otel instrumentation

- .devops/cstar-rtd-deploy-pipelines.yml
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/telemetry/AppInsightConfig.java
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
* enable opentelemetry with mongodb traces
* added logging
* using appinsight env variable to set role
* add role name from artifactId
* add role name from artifactId
* add role name from artifactId
* restore anchore.yml
* fix newman node>=16
* fix property appinsight enabled
* added metrics filter to essentials
> chore: [RTD-1957] otel instrumentation (#78)

- .devops/cstar-rtd-deploy-pipelines.yml
- .github/workflows/anchore.yml
> Promote to PROD

- .github/workflows/cve-scan.yml
- Dockerfile.native
- pom.xml
This PR upgrade spring boot from 3.0.4 to 3.1.4 and base image to resolve some high and critical CVEs
| dep | old | new | 
|----|----|----|
| spring boot | 3.0.4| 3.1.4 |
| opentelemetry | 1.30.0 | 1.31.0 |
| base image | ubuntu:jammy | ubuntu:mantic |
> fix: [RTD-2142] Upgrade spring boot & base image

- .github/workflows/cve-scan.yml
- Dockerfile.native
- pom.xml
* bump base image + bump spring boot
* bump opentelemetry to 1.31.0
* fix cve scan
> fix: [RTD-2142] Upgrade spring boot & base image (#93)

- helm/rtd/values-prod.yaml
> chore: helm chart image tag version

- helm/rtd/values-prod.yaml
> chore: wrong version prod helm

- pom.xml
Update dependencies
| Dependecy | Previews version | Updated version | 
| --- | --- | --- |
| `spring boot` | `3.1.4` | `3.2.1` |
| `snakeyaml ` | `2.0` | `2.2` |
| `testcontainers ` | `1.17.6` | `1.19.3` |
| `testcontainers-junit-jupiter ` | `1.17.6` | `1.19.3` |
| `mongodb ` | `1.17.6` | `1.19.3` |
> chore: [RTD-2310] update spring boot

- .github/workflows/cve-scan.yml
> chore: fix cve scan when no cve found

- .github/workflows/cve-scan.yml
> chore: fix cve scan when no cve found (#112)

- Dockerfile.native
- pom.xml
This PR proposes to update the spring boot version and the docker image runtime.
| dep | old version | new version |
| -- | -- | -- | 
| spring boot | 3.2.1 | 3.2.3|
| image runtime | ubuntu:mantic | ubuntu:noble-20240225|
> fix: [RTD-2457] fix CVE high on spring boot

- helm/rtd/values-dev.yaml
- helm/rtd/values-prod.yaml
- helm/rtd/values-uat.yaml
> chore: Add pod affinity for prod environment

- Dockerfile.native
- helm/rtd/values-dev.yaml
- helm/rtd/values-prod.yaml
- helm/rtd/values-uat.yaml
- pom.xml
> fix: promotion to UAT - fix cve

- .github/workflows/cve-scan.yml
- .github/workflows/release.yml
- Dockerfile
- Dockerfile.native
- pom.xml
> fix: [RTD-2475] update spring boot

- helm/rtd/values-prod.yaml
> chore: bump image to 1.1.5

- helm/rtd/values-prod.yaml
> bump image to 1.1.5 (#129)

- helm/rtd/values-prod.yaml
> chore: bump image to 1.1.5 (#129) (#130)

- Dockerfile.native
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/telemetry/AppInsightConfig.java
- src/main/resources/application.yml
- update OTEL and exporter
- disable metric collection
- update GraalVM image
> chore: [RTD-2480] bump OTEL and exporter version

- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- .github/workflows/scan.yml
- .github/workflows/send-notification.yml
- Dockerfile.native
- pom.xml
This pr split scan action and updates dependencies, images, and actions.
> chore: [RTD-2570] split action scan in 2 separate actions

- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/controller/SenderRestControllerImpl.java
> chore: [RTD-2580] increase log level

- .github/workflows/scan.yml
- pom.xml
> chore: [RTD-289] fix cve and github action

- .github/workflows/release.yml
- .github/workflows/scan.yml
- Dockerfile.native
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/telemetry/AppInsightConfig.java
- src/main/resources/application.yml
- upgrade spring boot to 3.3.4
- upgrade opentelemetry to 1.43.0
- upgrade opentelementry-instrumentation to 2.9.0 (target SDK 1.43.0)
- upgrade azure exporter to 1.0.0-beta.30 (target SDK 1.43.0)
- upgrade github actions
- removed mongodb manual instrumentation cause 2.9.0 provide it automatically
> fix: bump to spring boot 3.3.4

- .github/workflows/release.yml
- .github/workflows/scan.yml
- Dockerfile.native
- helm/rtd/values-prod.yaml
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmssenderauth/telemetry/AppInsightConfig.java
- src/main/resources/application.yml
> chore: wrong image tag
